# This file exists as a compatibility shim since this repository was not being versioned to allow breakages.

name: 'Build a rock'
description: 'Pack an OCI image with Rockcraft'
author: 'Canonical'
inputs:
  path:
    description: >
      The location of the Rockcraft project.

      Defaults to the base of the repository.
    default: '.'
  verbosity:
    description: >
      Set the build verbosity level to 'quiet', 'brief', 'verbose', 'debug' or
      'trace'.

      The default is 'trace'.
    default: 'trace'
  rockcraft-channel:
    description: >
      Install the snap from a specific channel

      If not provided, it defaults to stable.
    default: 'stable'
  revision:
    description: >
      Pin the snap revision to install.

      If not provided, it defaults to whatever revision is in latest/stable.
    default: ''
  test:
    description: >
      Run rockcraft test when packing the rock.

      If not provided, it defaults to false.
    default: 'false'
  pro:
    description: >
      The Ubuntu Pro services to enable when packing the rock.

      If not provided, no Ubuntu Pro services will be enabled.
    default: ''
  ignore:
    description: >
      Bypass a restriction to use an unsupported feature.

      For example, 'unmaintained' will ignore that the base is unmaintained.

      If not provided, it defaults to empty.
    default: ''
outputs:
  rock:
    description: 'The file name of the resulting rock.'
    value: ${{ steps.pack.outputs.rock }}
runs:
  using: 'composite'
  steps:
    - name: Deprecation notice
      shell: bash
      run: |
          echo "::warning::rockcraft-pack is deprecated and will be removed in a future release. Please migrate to rockcraft/pack instead."
    # This action is necessary as a workaround for https://github.com/actions/runner/issues/895.
    # Since contexts cannot be used in the `uses:` key, we can't guarantee that this action will
    # use the same branch of craft-actions to call other craft-actions workflows without just
    # making our own local copy of the repository. See https://github.com/canonical/craft-actions/pull/45#discussion_r2586507869
    # for a full explanation.
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      env:
        GITHUB_REF: ${{ github.action_ref }}
      with:
        repository: 'canonical/craft-actions'
        ref: ${{ env.GITHUB_REF }}
        path: _tmp_craft-actions
        sparse-checkout: |
          rockcraft/

    - uses: ./_tmp_craft-actions/rockcraft/pack
      id: pack
      with:
        path: ${{ inputs.path }}
        verbosity: ${{ inputs.verbosity }}
        channel: ${{ inputs.rockcraft-channel }}
        revision: ${{ inputs.revision }}
        test: ${{ inputs.test }}
        pro: ${{ inputs.pro }}
        ignore: ${{ inputs.ignore }}

    - shell: bash
      if: always()
      run: |
        rm -rf ./_tmp_craft-actions
branding:
  icon: layers
  color: orange
