packages:
  - "common"
  - "charmcraft/setup"
  - "imagecraft/setup"
  - "rockcraft/pack"
  - "rockcraft/setup"
  - "snapcraft/setup"

allowBuilds:
  esbuild: true

catalog:
  '@actions/core': "^3.0.0"
  '@actions/exec': "^3.0.0"
