packages:
  - "common"
  - "charmcraft/setup"
  - "charmcraft/pack"
  - "imagecraft/setup"
  - "imagecraft/pack"
  - "rockcraft/setup"
  - "rockcraft/pack"
  - "snapcraft/setup"
  - "snapcraft/pack"

allowBuilds:
  esbuild: true

catalog:
  "@actions/core": "^3.0.0"
  "@actions/exec": "^3.0.0"
