name: "Setup Charmcraft"
description: "Install Charmcraft"
author: "Canonical"
inputs:
  channel:
    description: >
      The channel to install Charmcraft from.

      If empty, the default channel for Charmcraft is used.
    default: ''
  revision:
    description: >
      Pin the snap revision to install.

      If not provided, it defaults to whatever revision is in latest/stable.
    default: ''
  lxd-channel:
    description: >
      The LXD channel to use.

      If empty, snapd's default channel for LXD is used.
    default: ''
outputs:
  lxd-revision:
    description: The LXD revision used.
  charmcraft-revision:
    description: The Charmcraft revision used.
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: package
  color: orange
