name: "Setup Charmcraft"
description: "Install Charmcraft"
author: "Canonical"
inputs:
  channel:
    description: >
      Install the snap from a specific channel

      If not provided, it defaults to stable.
    default: 'latest/stable'
  revision:
    description: >
      Pin the snap revision to install.

      If not provided, it defaults to whatever revision is in latest/stable.
    default: ''
  lxd-channel:
    description: >
      The LXD channel to use.

      Defaults to the recommended channel for Charmcraft.
    default: 5.21/stable
outputs:
  lxd-revision:
    description: The LXD revision used.
  charmcraft-revision:
    description: The Charmcraft revision used.
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: package
  color: orange
