name: 'Set up Rockcraft'
description: 'Install Rockcraft'
author: 'Canonical'
inputs:
  channel:
    description: >
      The channel to install Rockcraft from.

      If empty, the default channel for Rockcraft is used.
    default: ''
  revision:
    description: >
      The revision of Rockcraft to install.

      Defaults to the latest stable revision.

      Overrides the `channel` option.
    default: ''
  lxd-channel:
    description: >
      The channel to install LXD from.

      If empty, snapd's default channel for LXD is used.
    default: ''

outputs:
  lxd-revision:
    description: The LXD revision used.
  rockcraft-revision:
    description: The Rockcraft revision used.

runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: layers
  color: orange
