name: 'Set up Rockcraft'
description: 'Install Rockcraft'
author: 'Canonical'
inputs:
  channel:
    description: >
      The channel to install Rockcraft from.

      Defaults to the latest stable release.
    default: 'latest/stable'
  revision:
    description: >
      The revision of Rockcraft to install.

      Defaults to the latest stable revision.

      Overrides the `channel` option.
    default: ''
  lxd-channel:
    description: >
      The channel to install LXD from.

      Defaults to the recommended channel for Rockcraft.
    default: '5.21/stable'
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: layers
  color: orange
