name: 'Build a snap'
description: 'Pack a snap with Snapcraft'
author: Canonical

inputs:
  path:
    description: >
      The location of the Snapcraft project.

      Defaults to the root of the repository.
    default: '.'
  verbosity:
    description: >
      The build verbosity level, which can be set to "quiet", "brief", "verbose", "debug",
      or "trace".

      The default is "trace".
    default: 'trace'
  channel:
    description: >
      The channel to install Snapcraft from.

      Defaults to the latest stable release.
    default: 'latest/stable'
  revision:
    description: >
      The revision of Snapcraft to install.

      Defaults to the latest stable revision.

      Overrides the `channel` option.
    default: ''
  lxd-channel:
    description: >
      The channel to install LXD from.

      Defaults to the recommended channel for Snapcraft.
    default: '5.21/stable'

outputs:
  lxd-revision:
    description: The LXD revision used.
    value: ${{ steps.setup.outputs.lxd-revision }}
  snapcraft-revision:
    description: The Snapcraft revision used.
    value: ${{ steps.setup.outputs.snapcraft-revision }}
  snap:
    description: The packed snap artifact.
    value: ${{ steps.pack.outputs.snap }}
  components:
    description: The packed components.
    value: ${{ steps.pack.outputs.components }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v6
      env:
        GITHUB_REF: ${{ github.action_ref }}
      with:
        repository: 'canonical/craft-actions'
        ref: ${{ env.GITHUB_REF }}
        path: _tmp_craft-actions
        sparse-checkout: |
          snapcraft/

    - uses: ./_tmp_craft-actions/snapcraft/setup
      id: setup
      with:
        channel: ${{ inputs.channel }}
        revision: ${{ inputs.revision }}
        lxd-channel: ${{ inputs.lxd-channel }}

    - shell: bash
      run: |
        rm -rf ./_tmp_craft-actions

    - shell: bash
      id: pack
      env:
        CRAFT_VERBOSITY_LEVEL: ${{ inputs.verbosity }}
      working-directory: ${{ inputs.path }}
      run: |
        snapcraft pack
        echo "snap=$(ls *.snap)" >> "$GITHUB_OUTPUT"
        echo "components=$(ls -1 *.comp | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

branding:
  icon: package
  color: orange
