name: Check policy
on:
  pull_request:
  push:
    branches:
      - main
      - hotfix/*
      - work/check-policy # For development

jobs:
  policy:
    uses: canonical/starflow/.github/workflows/policy.yaml@main
  osv-scanner:
    name: Security scan / OSV-scanner
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install OSV scanner
        run: sudo snap install osv-scanner
      - name: Scan source
        run: |
          osv-scanner scan --recursive --allow-no-lockfiles \
            --config=osv-scanner.toml \
            --experimental-exclude docs \
            .
