name: Test the actions

on:
  pull_request:
  push:
    branches:
      - main
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"

jobs:
  test-action-code:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 24
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Check the formatting
      run: pnpm format-check
    - name: Lint the code
      run: pnpm lint
    - name: Run the unit tests
      run: pnpm test
    - name: Try to package code
      run: pnpm build
    - name: Ensure packaged code is committed
      run: git diff --exit-code

  run-rockcraft-pack-action:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
        revision: ['1206', '']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: Build a rock
      uses: ./rockcraft-pack
      id: rockcraft
      with:
        path: tests
        verbosity: debug
        revision: ${{ matrix.revision }}
    - name: Assert revision number
      if: matrix.revision != ''
      run: |
        set -ex
        installed_rev="$(snap info rockcraft | tail -1 | awk '{print $(NF-2)}')"
        [ "$installed_rev" == "(${{ matrix.revision }})" ]
    - name: Upload rock
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-rock-${{ matrix.os }}-${{ matrix.revision }}
        path: ${{ steps.rockcraft.outputs.rock }}

  run-rockcraft-pack-action-legacy-rock:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Build a legacy rock
        uses: ./rockcraft-pack
        id: rockcraft
        with:
          path: tests/legacy
          verbosity: debug
          ignore: 'unmaintained'
      - name: Upload legacy rock
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-legacy-rock-${{ matrix.os }}
          path: ${{ steps.rockcraft.outputs.rock }}
