name: 'Set up Snapcraft'
description: 'Install Snapcraft'
author: 'Canonical'
inputs:
  channel:
    description: >
      The channel to install Snapcraft from.

      If empty, the default channel for Snapcraft is used.
    default: ''
  revision:
    description: >
      The revision of Snapcraft to install.

      Overrides the `channel` option.
    default: ''
  lxd-channel:
    description: >
      The channel to install LXD from.

      If empty, snapd's default channel for LXD is used.
    default: ''

outputs:
  lxd-revision:
    description: The LXD revision used.
  snapcraft-revision:
    description: The Snapcraft revision used.

runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: package
  color: orange
