name: 'Set up Snapcraft'
description: 'Install Snapcraft'
author: 'Canonical'
inputs:
  channel:
    description: >
      The channel to install Snapcraft from.

      Defaults to the latest stable release.
    default: 'latest/stable'
  revision:
    description: >
      The revision of Snapcraft to install.

      Defaults to the latest stable revision.

      Overrides the `channel` option.
    default: ''
  lxd-channel:
    description: >
      The channel to install LXD from.

      Defaults to the recommended channel for Snapcraft.
    default: '5.21/stable'

outputs:
  lxd-revision:
    description: The LXD revision used.
    value: ${{ steps.lxd-revision.outputs.revision }}
  snapcraft-revision:
    description: The Snapcraft revision used.
    value: ${{ steps.snapcraft-revision.outputs.revision }}

runs:
  using: 'composite'
  steps:
    - shell: bash
      name: Check system compatibility
      run: |
        if [[ $(uname -s) != Linux ]]; then
          echo "::error::This action only works on Linux-based runners."
          exit 1
        fi

        if ! which snap; then
          echo "::error::This action requires snapd"
          exit 1
        fi

    - uses: actions/checkout@v6
      env:
        GITHUB_REF: ${{ github.action_ref }}
      with:
        repository: 'canonical/craft-actions'
        ref: ${{ env.GITHUB_REF }}
        path: _tmp_craft-actions
        sparse-checkout: |
          _common/

    - uses: canonical/setup-lxd@main
      with:
        channel: ${{ inputs.lxd-channel }}

    - shell: bash
      name: Install Snapcraft
      id: install
      run: |
        if [ -x /snap/bin/snapcraft ]; then
          ACTION=refresh
        else
          ACTION=install
        fi

        if [ -n "${{ inputs.revision }}" ]; then
          echo "::notice::Installing Snapcraft revision \"${{ inputs.revision }}\""
          sudo snap $ACTION --revision=${{ inputs.revision }} --classic snapcraft
        else
          echo "::notice::Installing Snapcraft from channel \"${{inputs.channel}}\""
          sudo snap $ACTION --channel=${{ inputs.channel }} --classic snapcraft
        fi

    - uses: ./_tmp_craft-actions/_common/get-snap-revision
      name: Get Snapcraft revision
      id: snapcraft-revision
      with:
        snap: 'snapcraft'

    - uses: ./_tmp_craft-actions/_common/get-snap-revision
      name: Get LXD revision
      id: lxd-revision
      with:
        snap: 'lxd'

    - shell: bash
      run: |
        rm -rf ./_tmp_craft-actions

branding:
  icon: package
  color: orange
